"""Add email to existing users

Revision ID: 6288aee08b84
Revises: c93de4b2fde9
Create Date: 2025-04-04 12:17:53.771469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6288aee08b84'
down_revision = 'c93de4b2fde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        connection = op.get_bind()
        connection.execute(
            sa.text("UPDATE \"user\" SET email = username || '@example.com' WHERE email IS NULL")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
